name: wetty
base: core20
adopt-info: wetty
summary: Terminal in browser over http/https.
description: |
  Terminal over HTTP and https. WeTTY is an alternative to ajaxterm and
  anyterm but much better than them because WeTTY uses xterm.js which is a
  full fledged implementation of terminal emulation written entirely in
  JavaScript. WeTTY uses websockets rather then Ajax and hence better
  response time.

confinement: strict

parts:
  wetty:
    plugin: npm
    npm-node-version: 14.17.3
    source: https://github.com/butlerx/wetty/archive/refs/tags/v2.3.0.tar.gz
    build-packages:
      - jq
    override-pull: |
      snapcraftctl pull
      version=$(cat package.json | jq -r '.version')
      snapcraftctl set-version "$version"
      snapcraftctl set-grade "stable"
    override-build: |
      # install the official nodejs so we get the expected npm version
      if [ $SNAP_ARCH == "amd64" ]; then
        ARCH=x64
      elif [ $SNAP_ARCH == "armhf" ]; then
        ARCH=armv7l
      elif [ $SNAP_ARCH == "ppc64el" ]; then
        ARCH=ppc64le
      else
        ARCH=$SNAP_ARCH
      fi
      curl -s https://nodejs.org/dist/v14.17.3/node-v14.17.3-linux-$ARCH.tar.gz | tar xzf - -C "$SNAPCRAFT_PART_INSTALL" --strip-components=1
      npm config set user 0
      npm config set unsafe-perm true
      npm install yarn
      export PATH=$SNAPCRAFT_PART_BUILD/node_modules/.bin:$PATH
      yarn
      yarn build
      yarn install --production --ignore-scripts --prefer-offline
      yarn pack -f wetty.tgz
      npm install -g --prefix "${SNAPCRAFT_PART_INSTALL}" wetty.tgz

  svc-script:
    plugin: dump
    source: snap/local
    stage-packages:
      - bash
    stage:
      - svc_wrapper.sh

hooks:
  configure:
    plugs: [network, network-bind]

apps:
  wetty:
    command: bin/wetty
    plugs: [network, network-bind]

  wettysvc:
    command: svc_wrapper.sh
    daemon: forking
    plugs: [network, network-bind]
